// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGJDo-7fSWDGMVuSUFUWUYiG1DFDr44OU',
    appId: '1:485784502151:web:4f6bc11106a309a7f01d22',
    messagingSenderId: '485784502151',
    projectId: 'carrentalandroid-afbaf',
    authDomain: 'carrentalandroid-afbaf.firebaseapp.com',
    storageBucket: 'carrentalandroid-afbaf.firebasestorage.app',
    measurementId: 'G-D70Z77RTZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAql7JeIFeqpmjGP-i-AmwV9AAnlVFHXDg',
    appId: '1:485784502151:android:afd020ee56d7583ef01d22',
    messagingSenderId: '485784502151',
    projectId: 'carrentalandroid-afbaf',
    storageBucket: 'carrentalandroid-afbaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNpDyy3Z_tQuI-XuljB4g0Y_h17ZzhOTc',
    appId: '1:485784502151:ios:8682453965b79328f01d22',
    messagingSenderId: '485784502151',
    projectId: 'carrentalandroid-afbaf',
    storageBucket: 'carrentalandroid-afbaf.firebasestorage.app',
    iosBundleId: 'com.example.carrentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGJDo-7fSWDGMVuSUFUWUYiG1DFDr44OU',
    appId: '1:485784502151:web:6aa2e343809247c2f01d22',
    messagingSenderId: '485784502151',
    projectId: 'carrentalandroid-afbaf',
    authDomain: 'carrentalandroid-afbaf.firebaseapp.com',
    storageBucket: 'carrentalandroid-afbaf.firebasestorage.app',
    measurementId: 'G-HV6XD8R08L',
  );
}
