// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        print('[FIREBASE] Loading Windows platform config');
        print('[FIREBASE] API Key: ${windows.apiKey.substring(0, 5)}...');
        print('[FIREBASE] Project ID: ${windows.projectId}');
        print('[FIREBASE] Auth Domain: ${windows.authDomain}');
        print('[FIREBASE] Storage Bucket: ${windows.storageBucket}');
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqVa2zyQ5jEBgH6QMXgfDkV1aYG_Cq8c4',
    appId: '1:744857559167:web:843af74a77670265ec5f4a',
    messagingSenderId: '744857559167',
    projectId: 'rentapp-df986',
    authDomain: 'rentapp-df986.firebaseapp.com',
    storageBucket: 'rentapp-df986.appspot.com',
    measurementId: 'G-J5L60GF847',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4tYiurVhnj_CgAfQZDuXN-grvVLN3ZW8',
    appId: '1:744857559167:android:726a8ebbc2032731ec5f4a',
    messagingSenderId: '744857559167',
    projectId: 'rentapp-df986',
    storageBucket: 'rentapp-df986.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_b-NTwUlFxwzCv1N7ANgc95s9kZO12sA',
    appId: '1:744857559167:ios:2a2a221063b9b2adec5f4a',
    messagingSenderId: '744857559167',
    projectId: 'rentapp-df986',
    storageBucket: 'rentapp-df986.appspot.com',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_b-NTwUlFxwzCv1N7ANgc95s9kZO12sA',
    appId: '1:744857559167:ios:2a2a221063b9b2adec5f4a',
    messagingSenderId: '744857559167',
    projectId: 'rentapp-df986',
    storageBucket: 'rentapp-df986.appspot.com',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqVa2zyQ5jEBgH6QMXgfDkV1aYG_Cq8c4',
    appId: '1:744857559167:web:7525eef7b0f03f52ec5f4a',
    messagingSenderId: '744857559167',
    projectId: 'rentapp-df986',
    authDomain: 'rentapp-df986.firebaseapp.com',
    storageBucket: 'rentapp-df986.appspot.com',
    measurementId: 'G-MHX14NQXNJ',
  );
}
